### SIGNUP

POST http://localhost:8080/api/users/signup HTTP/1.1
content-type: application/json

{
    "email": "cut@gmail.com",
    "name": "admin",
    # "role": "ADMIN",
    "password": "ReactJS",
    "passwordConfirm": "ReactJS"
    
}


### SIGNIN 

POST http://localhost:8080/api/users/signin HTTP/1.1
content-type: application/json

{
    "email": "cut@gmail.com",
    "password": "ReactJS"
}

### SINGLE 

GET http://localhost:8080/api/users/ HTTP/1.1

### DELETE A  
DELETE http://localhost:8080/api/users/ HTTP/1.1

### GET ALL users

GET http://localhost:8080/api/users?page=1&limit=5 HTTP/1.1


##################################HH################################################## HOTEL
### CREATE HOTEL

POST http://localhost:8080/api/hotels HTTP/1.1
content-type: application/json

{
  "name": "Bidemi hotel",
    "imageurls": [
      "https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_650,q_auto,w_1000/itemimages/44/87/44878_v3.jpeg",
      "https://media-cdn.tripadvisor.com/media/photo-s/10/77/57/9e/laudon.jpg"
    ],
    "rentperday": 3500,
    "type": "Deluxe",
    "maxcount": 2,
    "phonenumber": 6875357,
    "currentbookings": [],
    "description": "Stella hotel is located in Gaa-Kanbi Kwara state",
    "location": "Lagos"
}


### UPDATE HOTEL

PATCH http://localhost:8080/api/hotels/ HTTP/1.1
content-type: application/json

{
   "name": "Hotel Shiva",
    "imageurls": [
      "https://www.luxurytravelmagazine.com/files/610/2/2822/Sofitel_Paris_le_Faubourg_01_big_bu.jpg",
      "https://smallandeleganthotels.com/images/hotels/paris/_DSC9877b.jpg"
    ],
    "rentperday": 1500,
    "type": "Deluxe",
    "maxcount": 3,
    "phonenumber": 456986875357,
    "curremtbookings": [],
    "description": "Hotel Shiva is located in Badagry Lagos state",
    "location": "Lagos"
}

### SINGLE HOTEL

GET http://localhost:8080/api/hotels/ HTTP/1.1

### DELETE A HOTEL 
DELETE http://localhost:8080/api/hotels/ HTTP/1.1

### GET ALL HOTEL

GET http://localhost:8080/api/hotels?page=1&limit=20 HTTP/1.1

 

 