### SIGNUP

POST http://localhost:8080/api/users/signup HTTP/1.1
content-type: application/json

{
    "email": "Bola@gmail.com",
    "name": "admin",
    "role": "ADMIN",
    "password": "ReactJS",
    "passwordConfirm": "ReactJS"
    
}


### SIGNIN 

POST http://localhost:8080/api/users/signin HTTP/1.1
content-type: application/json

{
    "email": "bola@gmail.com",
    "password": "ReactJS"
}

### SINGLE 

GET http://localhost:8080/api/users/ HTTP/1.1

### DELETE A  
DELETE http://localhost:8080/api/users/ HTTP/1.1

### GET ALL users

GET http://localhost:8080/api/users?page=1&limit=5 HTTP/1.1


##################################HH################################################## HOTEL
### CREATE HOTEL

POST http://localhost:8080/api/hotels HTTP/1.1
content-type: application/json

{
  "name": "Bidemi hotel",
    "imageurls": [
      "https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_650,q_auto,w_1000/itemimages/44/87/44878_v3.jpeg",
      "https://media-cdn.tripadvisor.com/media/photo-s/10/77/57/9e/laudon.jpg"
    ],
    "rentperday": 3500,
    "type": "Deluxe",
    "maxcount": 2,
    "phonenumber": 6875357,
    "currentbookings": [],
    "description": "Stella hotel is located in Gaa-Kanbi Kwara state",
    "location": "Lagos"
}


### UPDATE HOTEL

PATCH http://localhost:8080/api/hotels/ HTTP/1.1
content-type: application/json

{
   "name": "Hotel Shiva",
    "imageurls": [
      "https://www.luxurytravelmagazine.com/files/610/2/2822/Sofitel_Paris_le_Faubourg_01_big_bu.jpg",
      "https://smallandeleganthotels.com/images/hotels/paris/_DSC9877b.jpg"
    ],
    "rentperday": 1500,
    "type": "Deluxe",
    "maxcount": 3,
    "phonenumber": 456986875357,
    "curremtbookings": [],
    "description": "Hotel Shiva is located in Badagry Lagos state",
    "location": "Lagos"
}

### SINGLE HOTEL

GET http://localhost:8080/api/hotels/ HTTP/1.1

### DELETE A HOTEL 
DELETE http://localhost:8080/api/hotels/ HTTP/1.1

### GET ALL HOTEL

GET http://localhost:8080/api/hotels?page=1&limit=20 HTTP/1.1



##################################HH################################################## BOOKING
### CREATE BOOKING

POST http://localhost:8080/api/bookings HTTP/1.1
content-type: application/json

{
        "room": "tryied this",
        "roomid": "6b9eb586-a5e6-4ca2-83ea-378d5bd888ab",
        "userid": "1c8fdca4-a1ef-4e62-9ed8-93fe8efb730d",
        "fromdate": "10-6-45",
        "todate": "12-6-45",
        "totalamount": 6500,
        "totaldays": 5,
        "transactionid": "12345"
}

### SINGLE BOOKING

GET http://localhost:8080/api/bookings/ba10d643-2af8-4374-910e-c078d86cfe95 HTTP/1.1

### CANCEL A BOOKING 
DELETE http://localhost:8080/api/bookings/ HTTP/1.1

### GET ALL BOOKING

GET http://localhost:8080/api/bookings?page=1&limit=20 HTTP/1.1

 

 